// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phltegslhhbdyxzupvyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobHRlZ3NsaGhiZHl4enVwdnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTY4OTEsImV4cCI6MjA2MDYzMjg5MX0.R5SZnNbcm35xYQ8ATKm6qilXtmWqwMlTkvHQvsFU7DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);